export const GET_FILE = "GET_FILE";
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS";
export const GET_FILE_FAIL = "GET_FILE_FAIL";

export const SELECT_FILE = "SELECT_FILE";
export const SELECT_FILES_SUCCESS = "SELECT_FILE_SUCCESS";
export const SELECT_FILES_FAIL = "SELECT_FILE_FAIL";

export const VIEW_FILE = "VIEW_FILE";
export const VIEW_FILE_SUCCESS = "VIEW_FILE_SUCCESS";
export const VIEW_FILE_FAIL = "VIEW_FILE_FAIL";

export const GET_FILES = "GET_FILES";
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS";
export const GET_FILES_FAIL = "GET_FILES_FAIL";

export const GET_USER_FILES = "GET_USER_FILES";
export const GET_USER_FILES_SUCCESS = "GET_USER_FILES_SUCCESS";
export const GET_USER_FILES_FAIL = "GET_USER_FILES_FAIL";

export const EDIT_FILE = "EDIT_FILE";
export const EDIT_FILE_SUCCESS = "EDIT_FILE_SUCCESS";
export const EDIT_FILE_FAIL = "EDIT_FILE_FAIL";

export const ADD_FILE = "ADD_FILE";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";
export const ADD_FILE_FAIL = "ADD_FILE_FAIL";

export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAIL = "DELETE_FILE_FAIL";

export const FILE_LOADING = "FILE_LOADING";
export const FILE_LOADING_SUCCESS = "FILE_LOADING_SUCCESS";
export const FILE_LOADING_FAIL = "FILE_LOADING_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const GET_ERRORS_SUCCESS = "GET_ERRORS_SUCCESS";
export const GET_ERRORS_FAIL = "GET_ERRORS_FAIL";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAIL = "SET_CURRENT_USER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
